transformations:
  - frame_id: base_link
    id: camera_color_optical_frame
    transform:
      - 0.000
      - 0.000
      - 0.500
      - 0.500
      - -0.500
      - 0.500
      - -0.500
  - frame_id: camera_color_optical_frame
    id: charger
    transform:
      - -0.06
      - 0.176
      - 0.320
      - 0.500
      - -0.500
      - 0.500
      - 0.500